# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rxeval, .registration = TRUE
NULL

#' Which expressions in a form will behave differently on a tablet than in
#' a browser.
#'
#' @param form Path to an XForm, or the XML itself.
#' @return A data frame with one row per issue: `path`, `rule`,
#'   `expression`, `construct`, `breaks`, `effect`, `suggestion`, `says`.
#'   Zero rows means the form travels.
rust_form_portability <- function(form) .Call(wrap__rust_form_portability, form)

#' What a form's own rules say about a submission.
#'
#' @param form Path to an XForm, or the XML itself.
#' @param submission Path to a submission, or its XML.
#' @param today,now What `today()` and `now()` should answer. Defaults to
#'   the submission's own metadata, so a date rule is judged against the
#'   day the work was done rather than the day of the check.
#' @return A data frame: `path`, `kind`, `says`. Zero rows means the
#'   submission satisfies every rule the engine could evaluate — and a
#'   rule it could not evaluate appears as kind `not-evaluated`, never as
#'   a pass.
rust_submission_findings <- function(form, submission, today, now) .Call(wrap__rust_submission_findings, form, submission, today, now)

#' Evaluate one XPath expression against a submission.
#'
#' For working out what a rule actually does before writing it into a
#' form.
#'
#' @param expression The XPath expression.
#' @param submission Path to a submission, or its XML.
#' @param today,now What `today()` and `now()` should answer.
#' @return A length-one character vector. An expression the engine cannot
#'   evaluate raises an error rather than returning a plausible value.
rust_eval_expression <- function(expression, submission, today, now) .Call(wrap__rust_eval_expression, expression, submission, today, now)

# nolint end
